# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://kiwicloud.ninja/"  # Include trailing slash
title = "kiwicloud.ninja"
# copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = ["github.com/chipzoller/hugo-clarity"]
# disqusShortname = ""

DefaultContentLanguage = "en"

enableEmoji = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
