[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "vCloud Director"
  url = "categories/vcloud-director"
  weight = -100

[[main]]
  name = "PowerShell"
  url = "categories/powershell"
  weight = -90

[[main]]
  name = "PowerCLI"
  url = "categories/powercli"
  weight = -80

[[main]]
  name = "vCloud Availability"
  url = "categories/vcloud-availability"
  weight = -70

[[main]]
  name = "About"
  url = "about/"
  weight = -50

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/jondwaite"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/jondwaite"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/jondwaite"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
